# Generated by Django 3.0.3 on 2020-02-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='AccountTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='todo.Account', verbose_name='Исполняющий')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewers', to='todo.Account', verbose_name='Ответственный')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('performer_mtm', models.ManyToManyField(related_name='tasks', through='todo.AccountTask', to='todo.Account')),
                ('reviewer_mtm', models.ManyToManyField(related_name='verifiable', through='todo.AccountTask', to='todo.Account')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.AddField(
            model_name='accounttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttask',
            unique_together={('performer', 'task')},
        ),
    ]
